name: RELEASE-WORKFLOW
on:
  release:
    types: [published]
jobs:
  other-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Release notification
        uses: stormwarning/action-release-notification@v1
        with:
          channel: releases
          message: A new version is out!
          actions: '[{"text": "View changelog 🎉", "url": "CHANGELOG.md"},{"text": "View docs 📚", "url": "https://foo.com"}]'
        env:
          SLACKBOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}

